### ISSUE TITLE
deface in Gemfile

### ISSUE THREAD

**Issue by rakhinskiy** [Undev/redmine_customize#5]
When I try bundle install I recive error 

Resolving dependencies............
Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    deface (< 1.0.0) ruby depends on
      nokogiri (~> 1.4.3) ruby

Can i change deface (< 1.0.0)  to deface or use deface 1.0.1?

**Comment by nodecarter** [comment]
Hi @rakhinskiy 
No you can't change deface gem requirements. Some plugin features will not work. https://github.com/spree/deface#upgrading-from-09-to-10
